parameters:
  hal.release.package.service.class : Hal\Bundle\ReleaseBundle\Service\PackageService
  hal.release.release.service.class : Hal\Bundle\ReleaseBundle\Service\ReleaseService
  hal.release.repository.composer.class : Hal\Bundle\ReleaseBundle\Repository\ReleaseRepositoryComposer
  hal.release.package.repository.class : Hal\Bundle\ReleaseBundle\Repository\PackageRepository
  hal.owner.service.class: Hal\Bundle\ReleaseBundle\Service\OwnerService

  hal.release.declaration.repository.class: Hal\Bundle\ReleaseBundle\Repository\DeclarationRepository
  hal.release.declaration.service.class: Hal\Bundle\ReleaseBundle\Service\DeclarationService
  hal.release.constraint.factory.class: Hal\Bundle\ReleaseBundle\Factory\ConstraintFactory

  hal.release.requirement.service.class: Hal\Bundle\ReleaseBundle\Service\RequirementService



services:



  # Package -> service
  hal.release.package.service:
    class: %hal.release.package.service.class%
    arguments:
      - @hal.release.package.repository

  # Package -> repository
  hal.release.package.repository:
      class: %hal.release.package.repository.class%
      arguments:
        - @doctrine.orm.entity_manager
        - @hal.release.constraint.factory

  # Release -> service
  hal.release.release.service:
    class: %hal.release.release.service.class%
    arguments: []

  # Constraint -> factory
  hal.release.constraint.factory:
    class: %hal.release.constraint.factory.class%
    arguments: []

  # Declaration -> repository
  hal.release.declaration.repository:
     class: %hal.release.declaration.repository.class%
     arguments:
     - @doctrine.orm.entity_manager

  # Declaration -> service
  hal.release.declaration.service:
    class: %hal.release.declaration.service.class%
    arguments:
    - @hal.release.declaration.repository
    - @hal.release.constraint.factory
    - @hal.release.package.service
    - @hal.release.release.service

  # Requirement -> service
  hal.release.requirement.service:
    class: %hal.release.requirement.service.class%
    arguments:
    - @hal.release.declaration.repository
