jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        hal_github_user:
          id: hal.github.security.user.provider


    firewalls:
        secured_area:
          pattern:   ^/
          anonymous: true
          logout:    true
          oauth:
              resource_owners:
                  github:        /login/check-github
              login_path:        /login
              failure_path:      /bad
              oauth_user_provider:
                  service: hal.github.security.user.provider

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
