Hal\ReleaseBundle\Entity\Requirement:
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: auto }
  fields:
    requiredVersion:
      type: constraint
    status:
      type: requirementstatus
  manyToOne:
    package:
      targetEntity: Package
      cascade: ["persist", "merge"]
    declaration:
      targetEntity: Declaration
      cascade: ["persist", "merge"]