parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     composout
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt


    github_app_id:       652f9a022ddb64dacd91
    github_app_secret:   21b7f4199b927079aedf8a4a15e9f772487b1f01
    github_redirect_url: http://composout/app_dev.php/github/auth

    github_options:
      display:
        recents:
          repository: 10
