hwi_oauth:
    firewall_name: secured_area
    resource_owners:
        github:
          type:                github
          client_id:           %github_app_id%
          client_secret:       %github_app_secret%
          scope:               "public_repo"