Hal\GithubBundle\Entity\Repository:
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: auto }
  fields:
    name:
      type: string
    gitUrl:
      type: string
    url:
      type: string
    private:
      type: integer
      length: 1
    enabled:
      type: integer
      length: 1
  manyToOne:
    owner:
      targetEntity: Owner
  oneToMany:
    branches:
      targetEntity: Branche
      mappedBy: repository
      cascade: ["persist", "merge"]
