parameters:
  hr.package.service.class : Hal\ReleaseBundle\Service\PackageService
  hr.release.repo.composer.class : Hal\ReleaseBundle\Repository\ReleaseRepositoryComposer
  hr.package.repo.class : Hal\ReleaseBundle\Repository\PackageRepository
  hr.owner.repo.class : Hal\ReleaseBundle\Repository\OwnerRepository
  hr.owner.service.class: Hal\ReleaseBundle\Service\OwnerService

services:
  hr.package.service:
    class: %hr.package.service.class%
    arguments: [@hr.package.repo.persistence]
  hr.package.repo.persistence:
      class: %hr.package.repo.class%
      arguments: [@doctrine.orm.entity_manager]
  hr.owner.repo.persistence:
        class: %hr.owner.repo.class%
        arguments: [@doctrine.orm.entity_manager]

  hr.owner.service:
      class: %hr.owner.service.class%
      arguments:
        - @hal.github.auth.service
        - @hal.github.user.service
        - @session
        - @hr.owner.repo.persistence